/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWalletRouteImport } from './routes/_app/wallet'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppMessagesIndexRouteImport } from './routes/_app/messages/index'
import { Route as AppJobsIndexRouteImport } from './routes/_app/jobs/index'
import { Route as AppProfilesUserIdRouteImport } from './routes/_app/profiles/$userId'
import { Route as AppMessagesJobIdRouteImport } from './routes/_app/messages/$jobId'
import { Route as AppJobsPostRouteImport } from './routes/_app/jobs/post'
import { Route as AppJobsJobIdRouteImport } from './routes/_app/jobs/$jobId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesIndexRoute = AppMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIndexRoute = AppJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilesUserIdRoute = AppProfilesUserIdRouteImport.update({
  id: '/profiles/$userId',
  path: '/profiles/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesJobIdRoute = AppMessagesJobIdRouteImport.update({
  id: '/messages/$jobId',
  path: '/messages/$jobId',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsPostRoute = AppJobsPostRouteImport.update({
  id: '/jobs/post',
  path: '/jobs/post',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsJobIdRoute = AppJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/wallet': typeof AppWalletRoute
  '/jobs/$jobId': typeof AppJobsJobIdRoute
  '/jobs/post': typeof AppJobsPostRoute
  '/messages/$jobId': typeof AppMessagesJobIdRoute
  '/profiles/$userId': typeof AppProfilesUserIdRoute
  '/jobs/': typeof AppJobsIndexRoute
  '/messages/': typeof AppMessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/wallet': typeof AppWalletRoute
  '/jobs/$jobId': typeof AppJobsJobIdRoute
  '/jobs/post': typeof AppJobsPostRoute
  '/messages/$jobId': typeof AppMessagesJobIdRoute
  '/profiles/$userId': typeof AppProfilesUserIdRoute
  '/jobs': typeof AppJobsIndexRoute
  '/messages': typeof AppMessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/wallet': typeof AppWalletRoute
  '/_app/jobs/$jobId': typeof AppJobsJobIdRoute
  '/_app/jobs/post': typeof AppJobsPostRoute
  '/_app/messages/$jobId': typeof AppMessagesJobIdRoute
  '/_app/profiles/$userId': typeof AppProfilesUserIdRoute
  '/_app/jobs/': typeof AppJobsIndexRoute
  '/_app/messages/': typeof AppMessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/dashboard'
    | '/settings'
    | '/wallet'
    | '/jobs/$jobId'
    | '/jobs/post'
    | '/messages/$jobId'
    | '/profiles/$userId'
    | '/jobs/'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/dashboard'
    | '/settings'
    | '/wallet'
    | '/jobs/$jobId'
    | '/jobs/post'
    | '/messages/$jobId'
    | '/profiles/$userId'
    | '/jobs'
    | '/messages'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/_app/wallet'
    | '/_app/jobs/$jobId'
    | '/_app/jobs/post'
    | '/_app/messages/$jobId'
    | '/_app/profiles/$userId'
    | '/_app/jobs/'
    | '/_app/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages/': {
      id: '/_app/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AppMessagesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/': {
      id: '/_app/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AppJobsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profiles/$userId': {
      id: '/_app/profiles/$userId'
      path: '/profiles/$userId'
      fullPath: '/profiles/$userId'
      preLoaderRoute: typeof AppProfilesUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages/$jobId': {
      id: '/_app/messages/$jobId'
      path: '/messages/$jobId'
      fullPath: '/messages/$jobId'
      preLoaderRoute: typeof AppMessagesJobIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/post': {
      id: '/_app/jobs/post'
      path: '/jobs/post'
      fullPath: '/jobs/post'
      preLoaderRoute: typeof AppJobsPostRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/$jobId': {
      id: '/_app/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AppJobsJobIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWalletRoute: typeof AppWalletRoute
  AppJobsJobIdRoute: typeof AppJobsJobIdRoute
  AppJobsPostRoute: typeof AppJobsPostRoute
  AppMessagesJobIdRoute: typeof AppMessagesJobIdRoute
  AppProfilesUserIdRoute: typeof AppProfilesUserIdRoute
  AppJobsIndexRoute: typeof AppJobsIndexRoute
  AppMessagesIndexRoute: typeof AppMessagesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWalletRoute: AppWalletRoute,
  AppJobsJobIdRoute: AppJobsJobIdRoute,
  AppJobsPostRoute: AppJobsPostRoute,
  AppMessagesJobIdRoute: AppMessagesJobIdRoute,
  AppProfilesUserIdRoute: AppProfilesUserIdRoute,
  AppJobsIndexRoute: AppJobsIndexRoute,
  AppMessagesIndexRoute: AppMessagesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
